//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.4
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
using AME.Models.Dto;
 
namespace AME.Models.Restaurant
{

    [JsonObject(MemberSerialization.OptIn)]
	public partial class CusGroupName : DataTableBase
    {

		[JsonProperty, Column(IsIdentity = true)]
		public int CusGroupID { get; set; }

		[JsonProperty, Column(StringLength =128)]
		public string CusGroupname { get; set; }

		[JsonProperty]
		public bool? UsePrice2 { get=> usePrice2==null?false: usePrice2; set=> usePrice2=value??false; }
		bool? usePrice2;

	}

}
