//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.0
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
using System.ComponentModel;
using AME.Models.Dto; 

namespace AME.Models.Entity
{

    /// <summary>
    /// 商品
    /// </summary>
    [Index("uk_BarCode", "BarCode", true)]
	[Index("uk_UserCode", "UserCode", true)]
	[JsonObject(MemberSerialization.OptIn)]
	public partial class Products : DataTableBase
	{

		[JsonProperty, Column(IsIgnore = true)]
		public string ibnumber { get; set; } = null;

		/// <summary>
		/// 商品标识
		/// </summary>
		[JsonProperty, Column(IsIdentity = true)]
		public int ProductID { get; set; }

		/// <summary>
		/// 条码
		/// </summary>
		[JsonProperty, Column(StringLength = 128)]
		[DisplayName("条码")]
		public string BarCode { get; set; }

		/// <summary>
		/// 编号
		/// </summary>
		[JsonProperty, Column(StringLength = 128)]
		[DisplayName("编号")]
		public string UserCode { get; set; }

		/// <summary>
		/// 商品名称
		/// </summary>
		[JsonProperty]
		[DisplayName("商品名称")]
		public string ProductName { get; set; }

		[JsonProperty]
		public string ProductName2 { get; set; }

        /// <summary>
        /// 编辑日期
        /// </summary>
        [DisplayName("编辑日期")]
        [JsonProperty]
		public string ProductName3 { get; set; } = DateTime.Now.ToString("yyyy-MM-dd");

        /// <summary>
        /// 保质期
        /// </summary>
        [DisplayName("保质期")]
        [JsonProperty]
		public string ProductName4 { get; set; }

		[JsonProperty]
		public string ProductName5 { get; set; }
		/// <summary>
		/// 成本价
		/// </summary>
		[JsonProperty, Column(DbType = "decimal(19,4)")]
		public decimal? PricePurchase { get; set; }

		/// <summary>
		/// 单价
		/// </summary>
		[JsonProperty, Column(DbType = "decimal(19,4)")]
		public decimal UnitPrice { get; set; }

		[JsonProperty, Column(DbType = "decimal(19,4)")]
		public decimal? UnitPrice2 { get; set; }

		[JsonProperty, Column(DbType = "decimal(19,4)")]
		public decimal? UnitPrice3 { get; set; }

		[JsonProperty, Column(DbType = "decimal(19,4)")]
		public decimal? UnitPrice4 { get; set; }

		[JsonProperty, Column(DbType = "decimal(19,4)")]
		public decimal? UnitPrice5 { get; set; }

		[JsonProperty, Column(DbType = "decimal(19,4)")]
		public decimal? UnitPrice6 { get; set; }

		[JsonProperty, Column(DbType = "decimal(19,4)")]
		public decimal? UnitPrice7 { get; set; }

		[JsonProperty, Column(DbType = "decimal(19,4)")]
		public decimal? UnitPrice8 { get; set; }

		[JsonProperty, Column(DbType = "decimal(19,4)")]
		public decimal? UnitPriceAVG { get; set; }

		[JsonProperty, Column(DbType = "decimal(19,4)")]
		public decimal? UnitPriceLast { get; set; }


		/// <summary>
		/// 税率
		/// </summary>
		[JsonProperty]
		public float? Tax { get => _Tax ?? 0; set => _Tax = value; }
        float? _Tax = 0.21f;

        /// <summary>
        /// 供应商标识
        /// </summary>
        [JsonProperty]
		public int? SupplierID { get => _SupplierID; set {
			if (_SupplierID == value) return;
			_SupplierID = value;
		} }
		private int? _SupplierID = 1;

		/// <summary>
		/// 类别标识
		/// </summary>
		public int? CategoryID { get; set; } = 1;

		/// <summary>
		/// 包装(每包12)
		/// </summary>
		[JsonProperty]
		public int QuantityPerUnit { get; set; } = 1;

		/// <summary>
		/// 大包装(每箱144)
		/// </summary>
		[JsonProperty]
		public int QuantityPerUnit2nd { get; set; } = 1;

		/// <summary>
		/// 库存
		/// </summary>
		[JsonProperty]
		public double? UnitsInStock { get => _UnitsInStock ?? 0; set => _UnitsInStock = value; }
        double? _UnitsInStock = 0;

        [JsonProperty]
		public double? UnitsOnOrder { get => _UnitsOnOrder ?? 0; set => _UnitsOnOrder = value; }
        double? _UnitsOnOrder = 0;

        [JsonProperty]
		public double? UnitsOnPurchase { get => _UnitsOnPurchase ?? 0; set => _UnitsOnPurchase = value; }
        double? _UnitsOnPurchase = 0;


        [JsonProperty]
		[DisplayName("状态")]
		public int? MarketingNO { get; set; } = 0;

		/// <summary>
		/// 断货 (True代表断货)
		/// </summary>
		[JsonProperty]
		public bool? Discontinued { get; set; } = false;

		/// <summary>
		/// 折扣
		/// </summary>
		[JsonProperty]
		public int? Discount { get => _Discount ?? 0; set => _Discount = value; }
        int? _Discount = 0;

        /// <summary>
        /// 折扣开始日期
        /// </summary>
        [JsonProperty]
		public DateTime? DtoStartDate { get; set; }

		/// <summary>
		/// 折扣结束日期
		/// </summary>
		[JsonProperty]
		public DateTime? DtoExipDate { get; set; }

		/// <summary>
		/// 备注,一般展示给内部看
		/// </summary>
		[JsonProperty, Column(StringLength =-1)]  
		public string Remark { get; set; }

		/// <summary>
		/// 最低库存,用作采购计划,库存警报
		/// </summary>
		[JsonProperty]
		public double? ReorderLevel { get; set; }

		/// <summary>
		/// 简化版存放位置
		/// </summary>
		[JsonProperty, Column(StringLength =100)]
        [DisplayName("存放位置")]
        public string StorageLocation { get; set; }

		/// <summary>
		/// 商品资料更新时间戳
		/// </summary>
		[JsonProperty, Column(StringLength =128)]
		public string timestamp { get; set; }

		/// <summary>
		/// 图片更新时间戳
		/// </summary>
		[JsonProperty, Column(StringLength =-1)]  
		public string Picture { get; set; }

		/// <summary>
		/// 备用存放JSON字段
		/// </summary>
		[JsonProperty, Column(StringLength =3000)]
		public string fjson { get; set; }

		[JsonProperty, Column(StringLength =3000)]
		public string fjson2 { get; set; }

		/// <summary>
		/// 商品表里不显示
		/// </summary>
		[JsonProperty]
		public bool? hide { get; set; }

		[JsonProperty]
        public string Leng2ProductName { get; set; }

		[JsonProperty]
        [DisplayName("产地")]
		public string Leng3ProductName { get; set; }

		[JsonProperty]
        [DisplayName("品质标签")]
		public string Leng4ProductName { get; set; }

		[JsonProperty]
        [DisplayName("重量标签")]
		public string Leng5ProductName { get; set; }

		[JsonProperty, Column(StringLength =500)]
        [DisplayName("备注2")]
        public string Leng2Remark { get; set; }

		[JsonProperty, Column(StringLength =500)]
        public string Leng3Remark { get; set; }

		[JsonProperty, Column(StringLength =500)]
        public string Leng4Remark { get; set; }

		[JsonProperty, Column(StringLength =500)]
        [DisplayName("活动")]
        public string Leng5Remark { get; set; }

		[JsonProperty, Column(StringLength =128)]
		public string BigProductID { get; set; }

		[JsonProperty, Column(StringLength =300)]
		public string colorsize { get; set; }
		[JsonProperty, Column(DbType = "decimal(19,4)")]
		public decimal? PriceFactory { get; set; }

		[JsonProperty, Column(DbType = "decimal(19,4)")]
		public decimal? PriceTransport { get; set; }

		[JsonProperty]
		public double? QuantityTotal { get; set; }

		/// <summary>
		/// 商品规格:高度
		/// </summary>
		[JsonProperty]
		public double? height { get; set; } = 0;

		/// <summary>
		/// 商品规格:宽度
		/// </summary>
		[JsonProperty]
		public double? width { get; set; } = 0;

		/// <summary>
		/// 商品规格:长度
		/// </summary>
		[JsonProperty]
		public double? length { get; set; } = 0;

		/// <summary>
		/// 商品规格:重量
		/// </summary>
		[JsonProperty]
		public double? weight { get; set; } = 0;

		[JsonProperty]
		public double? MaxBultos2nd { get; set; }

        [JsonProperty]
        public int? Option1 { get => _Option1 ?? 0; set => _Option1 = value; }
        int? _Option1 = 0;

        /// <summary>
        /// WMS拆箱警报
        /// </summary>
        [JsonProperty]
		public int? UnboxLevel { get; set; }

		/// <summary>
		/// 图片二进制(餐饮使用)
		/// </summary>
		[JsonProperty] //[JsonProperty, Column(DbType = "image")]
		public byte[] Image { get; set; }

		/// <summary>
		/// 查看次数统计
		/// </summary>
		[JsonProperty]
		public int? Views { get; set; } = 0;

		[JsonProperty, Column(StringLength =450)]
 		public Guid? UUID { get; set; }

		[JsonProperty]
		public int? SellerID { get; set; }

		/// <summary>
		/// [餐馆] 触摸按钮标签颜色
		/// </summary>
		[JsonProperty, Column(StringLength =128)]
		public string Color { get; set; }

		/// <summary>
		/// [餐馆] 限售
		/// </summary>
		[JsonProperty]
		public int? limit { get; set; }

		/// <summary>
		/// [餐馆] 今日限售数量
		/// </summary>
		[JsonProperty]
		public int? limitQty { get; set; }

		/// <summary>
		/// [餐馆] 父级
		/// </summary>
		[JsonProperty, Column(StringLength =128)]
		public string Parent { get; set; }

		/// <summary>
		/// +菜步进 (0.5 ,1) 半份 一份
		/// </summary>
		[JsonProperty]
		public float? Step { get; set; } = 1;

 		[JsonProperty]
		public int? Option2 { get; set; }

		[JsonProperty]
		public int? Option3 { get; set; }

		[JsonProperty]
		public int? Option4 { get; set; }

		[JsonProperty]
		public int? Option5 { get; set; }

		[JsonProperty]
		public int? Option6 { get; set; }

		[JsonProperty]
		public int? Option7 { get; set; }

		[JsonProperty]
		public int? Option8 { get; set; }

		[JsonProperty]
		public string OptionS1 { get; set; }

		[JsonProperty]
		public string OptionS2 { get; set; }

		/// <summary>
		/// 不含税价格
		/// </summary>
		[JsonProperty, Column(DbType = "decimal(19,4)")]
		public decimal? UnitPriceTaxExcluded { 
			get=> unitPriceTaxExcluded??0;
			set=> unitPriceTaxExcluded=value; 
		}
		decimal? unitPriceTaxExcluded;

		#region 外键 => 导航属性，ManyToOne/OneToOne


		[Navigate(nameof(CategoryID))]
		public virtual CategoriesNameOnly Categories { get; set; }
		
		#endregion

 	}
 
}
